language: node_js

node_js:
    - "node"
    - "8"
    - "7"

sudo: false

git:
    submodules: false

before_script:
    - cd redovisa && make install && cd ..

script:
    - cd redovisa && make test && cd ..
